{% set name = "chfem" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cortezpedro/chfem/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5ff18999332449cfe745a51e460efd7ea313d5cb99876d5fcadbda5d771fa11d

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [osx]
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  skip: true  # [linux and py<39]
  missing_dso_whitelist:
    - "*/nvcuda.dll"   # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - libgomp  # [linux]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - pip
    - setuptools
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ocl-icd-system  # [linux]

test:
  imports:
    - chfem
  requires:
    - cuda-version {{ cuda_compiler_version }}
    - pip
    - pytest
    - numpy
  commands:
    - pip check
    - python -m pytest
  source_files:
    - test/*

about:
  home: https://github.com/cortezpedro/chfem
  summary: 'Computational homogenization of material samples characterized via micro-CT.'
  description: |
    `chfem`, which stands for _Computational Homogenization with the image-based Finite Element Method_, is a software written in C and CUDA, wrapped in Python, for the computational homogenization of material samples characterized via $\mu$-CT. As it is, the effective properties that can be evaluated are:

    + Thermal conductivity $\rightarrow$ $\kappa\nabla^{2}u=0$
    + Linear elasticity $\rightarrow$ $\nabla\cdot\mathbf{C}\nabla\mathbf{u}=0$
    + Permeability $\rightarrow$ $\mu\nabla^{2}\mathbf{u}-\nabla p+\mathbf{b}=0$ ; $\nabla\cdot\mathbf{u} -\tau p=0$

    The program follows a lightweight matrix-free approach to image-based finite element analysis, exploring GPU resources with CUDA to achieve significant performance gains. Our end goal is to be able to run large problems ($10^9$ DOFs) with relatively acessible graphics cards. Following is a visualization of the output from a permeability simulation.

    <p align="center">
      <img src="https://github.com/cortezpedro/chfem/raw/dev/docs/source/chfem_example.png" width="100%"></img>
    </p>

    If you use `chfem` in your research, please use the following BibTeX entries to cite 
    [our paper](https://doi.org/10.1016/j.commatsci.2023.112021):

    ```Bibtex
    @article{toolkit2023,
        title = {Simulation toolkit for digital material characterization of large image-based microstructures},
        author = {Pedro C.F. Lopes and Rafael S. Vianna and Victor W. Sapucaia and Federico Semeraro and Ricardo Leiderman and André M.B. Pereira},
        journal = {Computational Materials Science},
        volume = {219},
        pages = {112021},
        year = {2023},
        publisher={Elsevier}
    }
    ```
    Developed at the _Laboratório de Computação Científica, Universidade Federal Fluminense_ (`LCC-UFF`). Niterói, Brazil.

    There are two repositories for this project, a [development one on Gitlab](https://gitlab.com/cortezpedro/chfem_gpu) and a 
    [mirror of this repository on Github](https://github.com/cortezpedro/chfem), mostly used to host the stable release tags, the tutorial and documentation.

  license: MIT
  license_file: LICENSE
  doc_url: https://chfem.readthedocs.io/
  dev_url: https://github.com/cortezpedro/chfem

extra:
  recipe-maintainers:
    - cortezpedro
    - fsemerar
