{% set name = "chfem" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cortezpedro/chfem/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 492acd0561054c5bdecc6b2f2694df9d32b430c784f6715a64722af9ea58ec3d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [osx]
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  skip: true  # [linux and py<39]
  missing_dso_whitelist:
    - "*/nvcuda.dll"   # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - libgomp  # [linux]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - pip
    - setuptools
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ocl-icd-system  # [linux]

test:
  imports:
    - chfem
  requires:
    - cuda-version {{ cuda_compiler_version }}
    - pip
    - pytest
    - numpy
  commands:
    - pip check
    - python -m pytest
  source_files:
    - test/*

about:
  home: https://github.com/cortezpedro/chfem
  summary: 'Computational homogenization of material samples characterized via micro-CT.'
  description: |
    Computational homogenization of material samples characterized via micro-CT.

  license: MIT
  license_file: LICENSE
  doc_url: https://chfem.readthedocs.io/
  dev_url: https://github.com/cortezpedro/chfem

extra:
  recipe-maintainers:
    - fsemerar
